### ISSUE TITLE
Error during ct-ng build

### ISSUE THREAD

**Issue by xianrecords2015** [giridhar123/Qt-Rpi4-Mac-Cross-Compile#1]
I have performed all the steps that was indicated. I am facing an error during ct-ng build. Here is the log:

Installing core C gcc compiler
[EXTRA]    Configuring core C gcc compiler
[EXTRA]    Building gcc
[EXTRA]    Installing gcc
[EXTRA]    Housekeeping for core gcc compiler
[EXTRA]       '' --> lib (gcc)   lib (os)
[INFO ]  Installing core C gcc compiler: done in 328.00s (at 22:11)
[INFO ]  =================================================================
[INFO ]  Installing C library
[INFO ]    =================================================================
[INFO ]    Building for multilib 1/1: ''
[EXTRA]      Configuring C library
[EXTRA]      Building C library
[ERROR]      ../sysdeps/nptl/pthread.h:719:47: error: argument 1 of type 'struct __jmp_buf_tag *' declared as a pointer [-Werror=array-parameter=]
[ERROR]      ../sysdeps/nptl/pthread.h:719:47: error: argument 1 of type 'struct __jmp_buf_tag *' declared as a pointer [-Werror=array-parameter=]
[ERROR]      ../sysdeps/nptl/pthread.h:719:47: error: argument 1 of type 'struct __jmp_buf_tag *' declared as a pointer [-Werror=array-parameter=]
[ERROR]      make[3]: *** [../Makerules:271: /Volumes/crosstool-ng/.build/armv8-rpi4-linux-gnueabihf/build/build-libc/multilib/tcb-offsets.h] Error 1
[ERROR]      make[3]: *** Waiting for unfinished jobs....
[ERROR]      make[3]: *** [../Makerules:271: /Volumes/crosstool-ng/.build/armv8-rpi4-linux-gnueabihf/build/build-libc/multilib/tlsdesc.h] Error 1
[ERROR]      make[3]: *** [../Makerules:271: /Volumes/crosstool-ng/.build/armv8-rpi4-linux-gnueabihf/build/build-libc/multilib/rtld-global-offsets.h] Error 1
[ERROR]      make[2]: *** [Makefile:470: csu/subdir_lib] Error 2
[ERROR]      make[1]: *** [Makefile:9: all] Error 2
[ERROR]   
[ERROR]  >>
[ERROR]  >>  Build failed in step 'Building for multilib 1/1: '''
[ERROR]  >>        called in step 'Installing C library'
[ERROR]  >>        called in step '(top-level)'
[ERROR]  >>
[ERROR]  >>  Error happened in: CT_DoExecLog[scripts/functions@376]
[ERROR]  >>        called from: glibc_backend_once[scripts/build/libc/glibc.sh@274]
[ERROR]  >>        called from: CT_IterateMultilibs[scripts/functions@1608]
[ERROR]  >>        called from: glibc_main[scripts/build/libc/glibc.sh@40]
[ERROR]  >>        called from: do_libc_main[scripts/build/libc.sh@33]
[ERROR]  >>        called from: main[scripts/crosstool-NG.sh@697]
[ERROR]  >>
[ERROR]  >>  For more info on this error, look at the file: 'build.log'
[ERROR]  >>  There is a list of known issues, some with workarounds, in:
[ERROR]  >>      https://crosstool-ng.github.io/docs/known-issues/
[ERROR]  >>
[ERROR]  >> NOTE: You configuration uses non-default patch sets. Please
[ERROR]  >> select 'bundled' as the set of patches applied and attempt
[ERROR]  >> to reproduce this issue. Issues reported with other patch
[ERROR]  >> set selections (none, local, bundled+local) are going to be
[ERROR]  >> closed without explanation.
[ERROR]  >>
[ERROR]  >>  If you feel this is a bug in crosstool-NG, report it at:
[ERROR]  >>      https://github.com/crosstool-ng/crosstool-ng/issues/
[ERROR]  >>
[ERROR]  >>  Make sure your report includes all the information pertinent to this issue.
[ERROR]  >>  Read the bug reporting guidelines here:
[ERROR]  >>      http://crosstool-ng.github.io/support/
[ERROR]   
[ERROR]  (elapsed: 22:22.00)
[22:22] / gmake: *** [/usr/local/bin/ct-ng:261: build] Error 2

**Comment by xianrecords2015** [comment]
Any thoughts ?

**Comment by giridhar123** [comment]
Hey, sorry if I didn't reply about this but I didn't get any notification about this.
Could you please upload the "build.log" file?

**Comment by xianrecords2015** [comment]
For some reason, I am not able to upload a file here. So I extracted the last few lines of the build.log where the error is listed

**Comment by clauderobi** [comment]
In my case, https://github.com/crosstool-ng/crosstool-ng/issues/1712#issuecomment-1109766431, if I build the TC using Ubuntu 18.04 I am fine. The native compiler seems to pay a role.

Look at the test directory, there are Dockerfiles allowing to compile under an old environment.

**Comment by xianrecords2015** [comment]
I am building under Mac OS as instructed by the post

**Comment by clauderobi** [comment]
Actually, I said Ubuntu 18.04, or 20.04 or whatever. But in actuality, this is just a proxy for the native tool chain, which is what really matters.

I do not use Mac OS I know there are different versions. And different native compiler versions. 

In your case, you could try to run a Linux VM and try at least if your configuration works. That will not give you a TC that runs under Mac OS ....

OTOH, from the 1st post, it appears that the issue is with warnings that are treated as errors. May be try with to disable `CT_GLIBC_ENABLE_WERROR`

**Comment by giridhar123** [comment]
> Actually, I said Ubuntu 18.04, or 20.04 or whatever. But in actuality, this is just a proxy for the native tool chain, which is what really matters.
> 
> I do not use Mac OS I know there are different versions. And different native compiler versions.
> 
> In your case, you could try to run a Linux VM and try at least if your configuration works. That will not give you a TC that runs under Mac OS ....
> 
> OTOH, from the 1st post, it appears that the issue is with warnings that are treated as errors. May be try with to disable `CT_GLIBC_ENABLE_WERROR`

This repository is intended to create a cross compile environment from Mac OS without using a VM.

> For some reason, I am not able to upload a file here. So I extracted the last few lines of the build.log where the error is listed

Have you checked that in "ct-ng menuconfig" under the "C-library" menu, the option "Enable -Werror during the build" is disabled?
What version of Mac OS are you using?

**Comment by xianrecords2015** [comment]
I did go a little further by disabling -Werror. I am now getting the following error:

[INFO ]  =================================================================
[INFO ]  Installing final gcc compiler
[EXTRA]    Configuring final gcc compiler
[EXTRA]    Building final gcc compiler
[ERROR]    clang: error: unsupported option '-print-multi-os-directory'
[ERROR]    clang: error: no input files
[EXTRA]    Installing final gcc compiler
[EXTRA]    Housekeeping for final gcc compiler
[EXTRA]       '' --> lib (gcc)   lib (os)
[INFO ]  Installing final gcc compiler: done in 458.00s (at 33:08)
[INFO ]  =================================================================
[INFO ]  Installing cross-gdb
[EXTRA]    Configuring cross gdb
[EXTRA]    Building cross gdb
[ERROR]    configure: error: no usable python found at /usr/bin/python3
[ERROR]    make[2]: *** [Makefile:9781: configure-gdb] Error 1
[ERROR]    make[1]: *** [Makefile:932: all] Error 2
[ERROR]   
[ERROR]  >>
[ERROR]  >>  Build failed in step 'Installing cross-gdb'
[ERROR]  >>        called in step '(top-level)'
[ERROR]  >>
[ERROR]  >>  Error happened in: CT_DoExecLog[scripts/functions@376]
[ERROR]  >>        called from: do_gdb_backend[scripts/build/debug/300-gdb.sh@346]
[ERROR]  >>        called from: do_debug_gdb_build[scripts/build/debug/300-gdb.sh@73]
[ERROR]  >>        called from: do_debug[scripts/build/debug.sh@35]
[ERROR]  >>        called from: main[scripts/crosstool-NG.sh@697]
[ERROR]  >>
[ERROR]  >>  For more info on this error, look at the file: 'build.log'
[ERROR]  >>  There is a list of known issues, some with workarounds, in:
[ERROR]  >>      https://crosstool-ng.github.io/docs/known-issues/
[ERROR]  >>
[ERROR]  >> NOTE: You configuration uses non-default patch sets. Please
[ERROR]  >> select 'bundled' as the set of patches applied and attempt
[ERROR]  >> to reproduce this issue. Issues reported with other patch
[ERROR]  >> set selections (none, local, bundled+local) are going to be
[ERROR]  >> closed without explanation.
[ERROR]  >>
[ERROR]  >>  If you feel this is a bug in crosstool-NG, report it at:
[ERROR]  >>      https://github.com/crosstool-ng/crosstool-ng/issues/
[ERROR]  >>
[ERROR]  >>  Make sure your report includes all the information pertinent to this issue.
[ERROR]  >>  Read the bug reporting guidelines here:
[ERROR]  >>      http://crosstool-ng.github.io/support/
[ERROR]   
[ERROR]  (elapsed: 34:34.00)
[34:34] / gmake: *** [/usr/local/bin/ct-ng:261: build] Error 2

**Comment by giridhar123** [comment]
[ERROR] configure: error: no usable python found at /usr/bin/python3

You must install python 3.

**Comment by giridhar123** [comment]
Any news?

**Comment by xianrecords2015** [comment]
Sorry. I had to step out of this for a moment. I am still getting the same error. I checked and I have both python setup.

% which python3
/usr/bin/python3

% which python
/usr/bin/python
