### ISSUE TITLE
Issue with configure on Mac OS

### ISSUE THREAD

**Issue by xianrecords2015** [giridhar123/Qt-Rpi4-Mac-Cross-Compile#2]
I have been stuck on the configure step in both 32bits and 64bits version of the RPI.

I have attached my error log as well as the toolchain.cmake (Had to rename it .txt to attach it). I had to reconfigure more links as it seems that the:

/Volumes/crosstool-ng/armv8-rpi4-linux-gnueabihf/armv8-rpi4-linux-gnueabihf/sysroot/usr/include/arm-linux-gnueabihf
and
/Volumes/crosstool-ng/armv8-rpi4-linux-gnueabihf/armv8-rpi4-linux-gnueabihf/sysroot/usr/lib/arm-linux-gnueabihf

are not recognized by the configure process

In this latest attempt, I have now a collect2: fatal error: cannot find 'ld' coming up.

Any thoughts on what might be going wrong ?

Thank you,

Christian

[toolchain.cmake.txt](https://github.com/giridhar123/Qt-Rpi4-Mac-Cross-Compile/files/9285842/toolchain.cmake.txt)
[CMakeError.log](https://github.com/giridhar123/Qt-Rpi4-Mac-Cross-Compile/files/9285843/CMakeError.log)

**Comment by xianrecords2015** [comment]
Any thoughts on this ? I am willing to pay for services to get my cross compile environment working.

**Comment by giridhar123** [comment]
I am so sorry. I am only watching this issue right now. My tutorial is tested on Raspberry Pi OS 32bit only. Let me read your errors and I will look for a solution.

**Comment by xianrecords2015** [comment]
[qtpi-build.zip](https://github.com/giridhar123/Qt-Rpi4-Mac-Cross-Compile/files/9354985/qtpi-build.zip)


I have attached the directory I use to build the QT for the RASPI in 64 bits.

The command I use is:

../qt6/configure -release -opengl es2 -qt-harfbuzz -qt-doubleconversion -no-use-gold-linker -skip qtscript -skip qtwayland -skip qtdatavis3d -nomake examples -device linux-rasp-pi4-aarch64 -device-option CROSS_COMPILE=/Volumes/crosstool-ng/aarch64-rpi4-linux-gnu/bin/aarch64-rpi4-linux-gnu- -qt-host-path  /Users/christianjoly/qt-host -extprefix /Users/christianjoly/qt-raspi -prefix /usr/local/qt6 -- -DCMAKE_TOOLCHAIN_FILE=/Users/christianjoly/toolchain.cmake

Toolchain file:

[toolchain.cmake.txt](https://github.com/giridhar123/Qt-Rpi4-Mac-Cross-Compile/files/9354990/toolchain.cmake.txt)

**Comment by giridhar123** [comment]
Why is your directory called "aarch64-linux-gnu" and not "armv8-rpi4-linux-gnueabihf"?
The name of a folder couldn't be a problem but maybe you are compiling with a different version of the compiler I used to make this guide or maybe you missed some configuration on crosstool-ng.
I tried this guide only with Raspbian OS (32 bit) and I don't know if this could work for 64 bit too.
Now I'm downloading your build directory so I can do a check with my compiler and sysroot.

**Comment by xianrecords2015** [comment]
My directory is called aarch64-rpi4-linux-gnu because my cross compiler built is for 64bits RPI as you can see in the device option.

**Comment by giridhar123** [comment]
Try to make a link to those files inside the lib folder. Use the command "ln -s path_to_crt1.o_inside_aarch64_linux_gnu path_to_sysroot_lib".
The variable "CMAKE_LIBRARY_PATH" is used by cmake to look for libraries. It is not used by the compiler itself.

**Comment by xianrecords2015** [comment]
I am still having issues. I am getting the following errors:

  The C++ compiler

    "/Volumes/crosstool-ng/aarch64-rpi4-linux-gnu/bin/aarch64-rpi4-linux-gnu-g++"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /Users/christianjoly/qtpi-build/CMakeFiles/CMakeTmp
    
    Run Build Command(s):/usr/local/bin/ninja cmTC_d6be1 && [1/2] Building CXX object CMakeFiles/cmTC_d6be1.dir/testCXXCompiler.cxx.o
    [2/2] Linking CXX executable cmTC_d6be1
    FAILED: cmTC_d6be1 
    : && /Volumes/crosstool-ng/aarch64-rpi4-linux-gnu/bin/aarch64-rpi4-linux-gnu-g++ --sysroot=/Users/christianjoly/sysroot -lGLESv2  CMakeFiles/cmTC_d6be1.dir/testCXXCompiler.cxx.o -o cmTC_d6be1   && :
    /Volumes/crosstool-ng/aarch64-rpi4-linux-gnu/lib/gcc/aarch64-rpi4-linux-gnu/11.3.0/../../../../aarch64-rpi4-linux-gnu/bin/ld.bfd: cannot find crt1.o: No such file or directory
    /Volumes/crosstool-ng/aarch64-rpi4-linux-gnu/lib/gcc/aarch64-rpi4-linux-gnu/11.3.0/../../../../aarch64-rpi4-linux-gnu/bin/ld.bfd: cannot find crti.o: No such file or directory
    /Volumes/crosstool-ng/aarch64-rpi4-linux-gnu/lib/gcc/aarch64-rpi4-linux-gnu/11.3.0/../../../../aarch64-rpi4-linux-gnu/bin/ld.bfd: cannot find -lGLESv2
    /Volumes/crosstool-ng/aarch64-rpi4-linux-gnu/lib/gcc/aarch64-rpi4-linux-gnu/11.3.0/../../../../aarch64-rpi4-linux-gnu/bin/ld.bfd: cannot find -lstdc++
    /Volumes/crosstool-ng/aarch64-rpi4-linux-gnu/lib/gcc/aarch64-rpi4-linux-gnu/11.3.0/../../../../aarch64-rpi4-linux-gnu/bin/ld.bfd: cannot find -lm
    /Volumes/crosstool-ng/aarch64-rpi4-linux-gnu/lib/gcc/aarch64-rpi4-linux-gnu/11.3.0/../../../../aarch64-rpi4-linux-gnu/bin/ld.bfd: cannot find -lgcc_s
    /Volumes/crosstool-ng/aarch64-rpi4-linux-gnu/lib/gcc/aarch64-rpi4-linux-gnu/11.3.0/../../../../aarch64-rpi4-linux-gnu/bin/ld.bfd: cannot find -lc
    /Volumes/crosstool-ng/aarch64-rpi4-linux-gnu/lib/gcc/aarch64-rpi4-linux-gnu/11.3.0/../../../../aarch64-rpi4-linux-gnu/bin/ld.bfd: cannot find -lgcc_s
    /Volumes/crosstool-ng/aarch64-rpi4-linux-gnu/lib/gcc/aarch64-rpi4-linux-gnu/11.3.0/../../../../aarch64-rpi4-linux-gnu/bin/ld.bfd: cannot find crtn.o: No such file or directory
    collect2: error: ld returned 1 exit status
    ninja: build stopped: subcommand failed.

It is not finding some libraries. Is there a path that I should be adding ?

**Comment by giridhar123** [comment]
Hello, you are compiling for aarch64 target host, using my tutorial you should compile for armv8. Have you followed correctly the step regarding the ct-ng configuration?
