### ISSUE TITLE
Error when compiling gcc

### ISSUE THREAD

**Issue by ApiTracer** [giridhar123/Qt-Rpi4-Mac-Cross-Compile#3]
Hi,

The make -j4 command of gcc 11 build failed. Can you help me with that ?

xgcc: fatal error: cannot execute 'cc1plus': execvp: No such file or directory
compilation terminated.
make[3]: *** [../../gcc-releases-gcc-11.2.0/gcc/cp/Make-lang.in:196: s-selftest-c++] Error 1
make[3]: *** Waiting for unfinished jobs....
-fself-test: 57254 pass(es) in 2.551099 seconds
echo timestamp > s-selftest-c
make[3]: Leaving directory '/home/pi/gcc11Build/gcc'
make[2]: *** [Makefile:4788: all-stage1-gcc] Error 2
make[2]: Leaving directory '/home/pi/gcc11Build'
make[1]: *** [Makefile:29076: stage1-bubble] Error 2
make[1]: Leaving directory '/home/pi/gcc11Build'
make: *** [Makefile:1009: all] Error 2

After retry :
Build/./gmp/.libs -L/home/pi/gcc11Build/./mpfr/src/.libs -L/home/pi/gcc11Build/./mpc/src/.libs -lmpc -lmpfr -lgmp -rdynamic -ldl  -L./../zlib -lz 
collect2: fatal error: ld terminated with signal 9 [Killed]
compilation terminated.
make[3]: *** [../../gcc-releases-gcc-11.2.0/gcc/lto/Make-lang.in:101: lto-dump] Error 1
make[3]: *** Waiting for unfinished jobs....
collect2: fatal error: ld terminated with signal 9 [Killed]
compilation terminated.
make[3]: *** [../../gcc-releases-gcc-11.2.0/gcc/cp/Make-lang.in:136: cc1plus] Error 1
make[3]: Leaving directory '/home/pi/gcc11Build/gcc'
make[2]: *** [Makefile:4788: all-stage1-gcc] Error 2
make[2]: Leaving directory '/home/pi/gcc11Build'
make[1]: *** [Makefile:29076: stage1-bubble] Error 2
make[1]: Leaving directory '/home/pi/gcc11Build'
make: *** [Makefile:1009: all] Error 2

**Comment by giridhar123** [comment]
Hello, I did not update this tutorial from some time. I will restore my MacBook and I will follow this tutorial to found new/old misstakes.
Thanks.

**Comment by ApiTracer** [comment]
Thanks for your help, I have found a workaround with ubuntu 20 Virtual machine and it works with Qt5, this is enough for now but I'm still interested for a native solution with Qt6.

**Comment by ApiTracer** [comment]
To be precise, the cross-compile on Ubuntu VM works with Qt6 but not the webengine module and I need it. 
So if we can try with this module also, it will be precious for me

**Comment by giridhar123** [comment]
I did the cross-compile environment on MacOS with Qt6 but I had some problems with webengine too.
I hope in this days to update the tutorial for Qt 6.4.2 with webengine.

**Comment by giridhar123** [comment]
Hello, today I restored my Mac and my Raspberry Pi. I did the same steps of my tutorial and I didn't encountered any errors. Are you still having that error when compiling gcc?
