### ISSUE TITLE
MacOs crosstool-ng gobjcopy and objcopy not found 

### ISSUE THREAD

**Issue by ApiTracer** [giridhar123/Qt-Rpi4-Mac-Cross-Compile#4]
For macOS side, I have this errors during configure of cross tool-ng :
checking for gobjcopy... no
checking for objcopy... no
configure: error: missing required tool: gobjcopy objcopy

**Comment by ApiTracer** [comment]
I install crosstool-ng with brew to avoid this but then, when I try the build, I have errors with x-tools aren't in the right dir (Volumes/crosstool-ng) : 
[WARN ]  Directory '/Users/username/src' does not exist.
[WARN ]  Will not save downloaded tarballs to local storage.
[EXTRA]  Preparing working directories
[ERROR]  Your file system in '/Users/username/x-tools/armv8-rpi4-linux-gnueabihf' is *not* case-sensitive!

**Comment by giridhar123** [comment]
Hello, have you created the new volume as "APFS - Case Sensitive"?
BTW, it looks like you are running the command in the main volume (where folder "Users" is located) and not on the volume "crosstool-ng".
You can refer to this link on how to create a Case Sensitive volume in MacOS.

https://www.youtube.com/watch?v=lqdob9BsjM4

**Comment by ApiTracer** [comment]
I think, I have done this right but I deleted this volumes after the workaround with ubuntu VM works... so I can retry easily.
If you update the tutorial, can you try with crosstool-ng from brew and rpi4 profile of crosstool ?

**Comment by giridhar123** [comment]
Sure.

**Comment by giridhar123** [comment]
I solved the problem related to "gobscopy" and "objcopy" adding these lines to my ".bash_profile" file.
https://github.com/giridhar123/Qt-Rpi4-Mac-Cross-Compile/commit/785cda9d3abf941d5a5356c5e48f51709b279870

I'm compiling the toolchain for rpi4 using croostool-ng using the rpi3 profile and editing it as I wrote in the tutorial.
BTW, did you make a try with a case sensitive volume?
